const NotificationData = [
    {
        "Id":"5b7b9bd7ca7c6c352ae2b1e8",
        "MemberId":330,
        "Message":"Today is Semi-Finals of Voice of RMZ at Amphitheatre, Ecoworld starting 12:30 PM. Come join and Vote for your favourite contestant in Talent Club -> Bud Club in the App. ",
        "HtmlMessage":"Today is Semi-Finals of Voice of RMZ at Amphitheatre, Ecoworld starting 12:30 PM. Come join and Vote for your favourite contestant in Talent Club -> Bud Club in the App. ",
        "AddedDate":1534827479084,
        "Status":1,
        "WebStatus":2,
        "ReadDate":null,
        "RelayType":1,
        "Parameters":{
            "Icon":"notification_icon",
            "Color":"#00979d",
            "Picture":"",
            "MemberId":6407,
            "SenderId":0,
            "Status":"",
            "Message":"Today is Semi-Finals of Voice of RMZ at Amphitheatre, Ecoworld starting 12:30 PM. Come join and Vote for your favourite contestant in Talent Club -> Bud Club in the App. ",
            "EventAction":"GENERAL",
            "Event":"COMMON",
            "_t":"COMMON"
        },
        "BadgeCount":0,
        "ImageUrl":null,
        "NotificationIds":[],
        "title":'Mail & Parcel', 
    },
    {
        "Id":"5b7b9bd7ca7c6c352ae2b1e8",
        "MemberId":330,
        "Message":"Today is Semi-Finals of Voice of RMZ at Amphitheatre, Ecoworld starting 12:30 PM. Come join and Vote for your favourite contestant in Talent Club -> Bud Club in the App. ",
        "HtmlMessage":"Today is Semi-Finals of Voice of RMZ at Amphitheatre, Ecoworld starting 12:30 PM. Come join and Vote for your favourite contestant in Talent Club -> Bud Club in the App. ",
        "AddedDate":1534827479084,
        "Status":1,
        "WebStatus":2,
        "ReadDate":null,
        "RelayType":1,
        "Parameters":{
            "Icon":"notification_icon",
            "Color":"#00979d",
            "Picture":"",
            "MemberId":6407,
            "SenderId":0,
            "Status":"",
            "Message":"Today is Semi-Finals of Voice of RMZ at Amphitheatre, Ecoworld starting 12:30 PM. Come join and Vote for your favourite contestant in Talent Club -> Bud Club in the App. ",
            "EventAction":"GENERAL",
            "Event":"COMMON",
            "_t":"COMMON"
        },
        "BadgeCount":0,
        "ImageUrl":null,
        "NotificationIds":[],
        "title":'Mail & Parcel', 
    },
    {
        "Id":"5b7b9bd7ca7c6c352ae2b1e8",
        "MemberId":330,
        "Message":"Today is Semi-Finals of Voice of RMZ at Amphitheatre, Ecoworld starting 12:30 PM. Come join and Vote for your favourite contestant in Talent Club -> Bud Club in the App. ",
        "HtmlMessage":"Today is Semi-Finals of Voice of RMZ at Amphitheatre, Ecoworld starting 12:30 PM. Come join and Vote for your favourite contestant in Talent Club -> Bud Club in the App. ",
        "AddedDate":1534827479084,
        "Status":1,
        "WebStatus":2,
        "ReadDate":null,
        "RelayType":1,
        "Parameters":{
            "Icon":"notification_icon",
            "Color":"#00979d",
            "Picture":"",
            "MemberId":6407,
            "SenderId":0,
            "Status":"",
            "Message":"Today is Semi-Finals of Voice of RMZ at Amphitheatre, Ecoworld starting 12:30 PM. Come join and Vote for your favourite contestant in Talent Club -> Bud Club in the App. ",
            "EventAction":"GENERAL",
            "Event":"COMMON",
            "_t":"COMMON"
        },
        "BadgeCount":0,
        "ImageUrl":null,
        "NotificationIds":[],
        "title":'Mail & Parcel',        
    },
    {
        "Id":"5b7b9bd7ca7c6c352ae2b1e8",
        "MemberId":330,
        "Message":"Today is Semi-Finals of Voice of RMZ at Amphitheatre, Ecoworld starting 12:30 PM. Come join and Vote for your favourite contestant in Talent Club -> Bud Club in the App. ",
        "HtmlMessage":"Today is Semi-Finals of Voice of RMZ at Amphitheatre, Ecoworld starting 12:30 PM. Come join and Vote for your favourite contestant in Talent Club -> Bud Club in the App. ",
        "AddedDate":1534827479084,
        "Status":1,
        "WebStatus":2,
        "ReadDate":null,
        "RelayType":1,
        "Parameters":{
            "Icon":"notification_icon",
            "Color":"#00979d",
            "Picture":"",
            "MemberId":6407,
            "SenderId":0,
            "Status":"",
            "Message":"Today is Semi-Finals of Voice of RMZ at Amphitheatre, Ecoworld starting 12:30 PM. Come join and Vote for your favourite contestant in Talent Club -> Bud Club in the App. ",
            "EventAction":"GENERAL",
            "Event":"COMMON",
            "_t":"COMMON"
        },
        "BadgeCount":0,
        "ImageUrl":null,
        "NotificationIds":[],
        "title":'Mail & Parcel', 
    }

]

export default NotificationData;